name: JSON Validator

on:
  pull_request:
    paths:
      - "public/data/projects.json"
      - "public/data/projects.schema.json"
  push:
    paths:
      - "public/data/projects.json"
      - "public/data/projects.schema.json"

jobs:
  verify-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate JSON files
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./public/data/projects.schema.json
          INPUT_JSONS: ./public/data/projects.json
