name: Next.js CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  deploy:
    name: Build and deploy to GH Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}
      - name: Use Node.js
        uses: actions/setup-node@v1
      - name: Install dependencies
        run: npm install
      - name: Build next.js app
        run: npm run build
      - name: Export static website
        run: npm run export
      - name: Generate sitemap
        run: gulp sitemap
      - name: Deploy website to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v4
        if: github.event_name == 'push'
        with:
          BRANCH: gh-pages
          FOLDER: out
          GIT_CONFIG_NAME: GitHub Actions
          GIT_CONFIG_EMAIL: noreply@github.com
          CLEAN: true
